In [3]:
import requests
import pandas as pd
import json

spacex_api_url = 'https://api.spacexdata.com/v4/launches'

print(f"Attempting to fetch data from: {spacex_api_url}")

try:
    
    response = requests.get(spacex_api_url)

    
    response.raise_for_status()

    
    spacex_data_json = response.json()

    print(f"\nSuccessfully fetched {len(spacex_data_json)} launch records from the SpaceX API.")
    print(f"Type of data after .json() decoding: {type(spacex_data_json)}")
    
    spacex_df = pd.json_normalize(spacex_data_json)

    # --- Outcome: Display DataFrame Information ---
    print("\n--- Outcome: SpaceX Launches DataFrame ---")
    print("DataFrame created successfully using pd.json_normalize().")

    print("\nFirst 5 rows of the DataFrame:")
    print(spacex_df.head())

    print("\nDataFrame Info (columns, non-null counts, data types):")
    spacex_df.info()

    print("\nShape of the DataFrame (rows, columns):", spacex_df.shape)


except requests.exceptions.HTTPError as http_err:
    print(f"HTTP error occurred: {http_err}")  # e.g., 404 Not Found, 500 Internal Server Error
except requests.exceptions.ConnectionError as conn_err:
    print(f"Connection error occurred: {conn_err}") # e.g., DNS failure, refused connection
except requests.exceptions.Timeout as timeout_err:
    print(f"Timeout error occurred: {timeout_err}")     # e.g., server did not send any data in the allotted amount of time
except requests.exceptions.RequestException as req_err:
    print(f"An unexpected error occurred during the request: {req_err}")
except json.JSONDecodeError as json_err:
    print(f"Error decoding JSON from the response: {json_err}")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

Attempting to fetch data from: https://api.spacexdata.com/v4/launches

Successfully fetched 205 launch records from the SpaceX API.
Type of data after .json() decoding: <class 'list'>

--- Outcome: SpaceX Launches DataFrame ---
DataFrame created successfully using pd.json_normalize().

First 5 rows of the DataFrame:
       static_fire_date_utc  static_fire_date_unix    net  window  \
0  2006-03-17T00:00:00.000Z           1.142554e+09  False     0.0
1                      None                    NaN  False     0.0
2                      None                    NaN  False     0.0
3  2008-09-20T00:00:00.000Z           1.221869e+09  False     0.0
4                      None                    NaN  False     0.0

                     rocket success  \
0  5e9d0d95eda69955f709d1eb   False
1  5e9d0d95eda69955f709d1eb   False
2  5e9d0d95eda69955f709d1eb   False
3  5e9d0d95eda69955f709d1eb    True
4  5e9d0d95eda69955f709d1eb    True

                                            failures  \
0  [{'time': 33, 'altitude': None, 'reason': 'mer...
1  [{'time': 301, 'altitude': 289, 'reason': 'har...
2  [{'time': 140, 'altitude': 35, 'reason': 'resi...
3                                                 []
4                                                 []

                                             details crew ships  ...  \
0   Engine failure at 33 seconds and loss of vehicle   []    []  ...
1  Successful first stage burn and transition to ...   []    []  ...
2  Residual stage 1 thrust led to collision betwe...   []    []  ...
3  Ratsat was carried to orbit on the first succe...   []    []  ...
4                                               None   []    []  ...

  links.reddit.media links.reddit.recovery links.flickr.small  \
0               None                  None                 []
1               None                  None                 []
2               None                  None                 []
3               None                  None                 []
4               None                  None                 []

   links.flickr.original                                     links.presskit  \
0                     []                                               None
1                     []                                               None
2                     []                                               None
3                     []                                               None
4                     []  http://www.spacex.com/press/2012/12/19/spacexs...

                                 links.webcast  links.youtube_id  \
0  https://www.youtube.com/watch?v=0a_00nJ_Y88       0a_00nJ_Y88
1  https://www.youtube.com/watch?v=Lk4zQ2wP-Nc       Lk4zQ2wP-Nc
2  https://www.youtube.com/watch?v=v0w9p3U8860       v0w9p3U8860
3  https://www.youtube.com/watch?v=dLQ2tZEH6G0       dLQ2tZEH6G0
4  https://www.youtube.com/watch?v=yTaIDooc8Og       yTaIDooc8Og

                                       links.article  \
0  https://www.space.com/2196-spacex-inaugural-fa...
1  https://www.space.com/3590-spacex-falcon-1-roc...
2  http://www.spacex.com/news/2013/02/11/falcon-1...
3               https://en.wikipedia.org/wiki/Ratsat
4  http://www.spacex.com/news/2013/02/12/falcon-1...

                                     links.wikipedia  fairings
0              https://en.wikipedia.org/wiki/DemoSat       NaN
1              https://en.wikipedia.org/wiki/DemoSat       NaN
2  https://en.wikipedia.org/wiki/Trailblazer_(sat...       NaN
3               https://en.wikipedia.org/wiki/Ratsat       NaN
4             https://en.wikipedia.org/wiki/RazakSAT       NaN

[5 rows x 43 columns]

DataFrame Info (columns, non-null counts, data types):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 43 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   static_fire_date_utc       121 non-null    object
 1   static_fire_date_unix      121 non-null    float64
 2   net                        205 non-null    bool
 3   window                     117 non-null    float64
 4   rocket                     205 non-null    object
 5   success                    186 non-null    object
 6   failures                   205 non-null    object
 7   details                    134 non-null    object
 8   crew                       205 non-null    object
 9   ships                      205 non-null    object
 10  capsules                   205 non-null    object
 11  payloads                   205 non-null    object
 12  launchpad                  205 non-null    object
 13  flight_number              205 non-null    int64
 14  name                       205 non-null    object
 15  date_utc                   205 non-null    object
 16  date_unix                  205 non-null    int64
 17  date_local                 205 non-null    object
 18  date_precision             205 non-null    object
 19  upcoming                   205 non-null    bool
 20  cores                      205 non-null    object
 21  auto_update                205 non-null    bool
 22  tbd                        205 non-null    bool
 23  launch_library_id          72 non-null     object
 24  id                         205 non-null    object
 25  fairings.reused            93 non-null     object
 26  fairings.recovery_attempt  107 non-null    object
 27  fairings.recovered         85 non-null     object
 28  fairings.ships             169 non-null    object
 29  links.patch.small          189 non-null    object
 30  links.patch.large          189 non-null    object
 31  links.reddit.campaign      150 non-null    object
 32  links.reddit.launch        164 non-null    object
 33  links.reddit.media         88 non-null     object
 34  links.reddit.recovery      95 non-null     object
 35  links.flickr.small         205 non-null    object
 36  links.flickr.original      205 non-null    object
 37  links.presskit             91 non-null     object
 38  links.webcast              188 non-null    object
 39  links.youtube_id           188 non-null    object
 40  links.article              142 non-null    object
 41  links.wikipedia            155 non-null    object
 42  fairings                   0 non-null      float64
dtypes: bool(4), float64(3), int64(2), object(34)
memory usage: 63.4+ KB

Shape of the DataFrame (rows, columns): (205, 43)